### ISSUE TITLE
Rename

### ISSUE THREAD

**Issue by jekor** [zalora/cl-aws#1]
As previously discussed, this name could lead to confusion with aws/aws-cli ("Is this a fork?"). Why don't we rename it cl-aws ("claws")?

**Comment by proger** [comment]
common lisp - aws ?:)

**Comment by phunehehe** [comment]
No problem with claws. I was thinking about something more boring like
haskell-aws-cli but I know I'm not creative with names.
Let's wait for a few days to see if anything other suggestion comes up.
